sudo: required
services:
    - docker

before_install:
    - docker build -t rm01964/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rm01964/docker-react npm run test -- --coverage

    deploy:
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-745232509913"
    on:
        branch: master
