sudo: required
services:
    - docker

before_install:
    - docker build -t rm01964/docker-react -f Dockerfile.dev .

script:
    - docker run rm01964/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-745232509913"
    bucket_path: "docker"
    on:
        branch: master
